version: "3.9"
services:
    web:
        build: .
        volumes:
            - ./app:/app
        ports:
            - "5000:5000"
    localtunnel:
        image: efrecon/localtunnel
        links:
            - web
        command:
            --local-host web --port 5000 --subdomain direferenceimplementation